# Numpy 

## Objectives

Know the main types of files with which we can work in Python.

• Know how to perform file reading and writing operations.

• Learn to use arrays one-dimensional and multi-dimensional .

• Differentiate the different dimensions of an array.

• Know the main numerical, vector and matrix calculation functions on arrays with Numpy

## What is Numpy

It is a library dedicated to numerical calculation in Python (__NUM__eric __PY__thon) .

* Provides data structures such as vectors and one-dimensional or multidimensional arrays.

* The objects (arrays) it generates are lighter in memory than lists.

* Arrays are faster to process than lists.

* A numeric operation is applied to an entire array.

* pip installation may be required __install numpy__

* Commonly used with the alias __np__

To import the library, use __import numpy as np__

![numpy_logo.png](attachment:numpy_logo.png)

In [ ]:
# !pip install numpy

In [ ]:
# Import the library
import numpy

In [ ]:
# Create our fist array

arr = numpy.array([10, 20, 98, 34])

arr

array([10, 20, 98, 34])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


Something very widespread among the Python developer community is to use __alias__ in the libraries, to shorten their name and identify them more easily, in the case of __numpy__ we will use the alias __np__

In [ ]:
import numpy as np

In [ ]:
# Create again the array
arr = np.array([23, 42, 58])

arr

array([23, 42, 58])

![numpy-anatomy-of-an-array-updated.png](attachment:numpy-anatomy-of-an-array-updated.png)

Some curiosities of arrays against lists, let's create a new list

In [ ]:
my_list = [1, 10, 20, 75]

Now, try to multiply each element by 2

In [ ]:
# my_list*2 

You'll need a foor loop to multiply each element

In [ ]:
for item in my_list:
    print(item*2)

2
20
40
150


But, if we've an array...

In [ ]:
my_arr = np.array([1, 10, 20, 75])

In [ ]:
my_arr*2

array([  2,  20,  40, 150])

## Different Data Structures as Arrays

### 1. Tuple

In [ ]:
my_tuple = (1, 58, 63, 45)
print(type(my_tuple))

<class 'tuple'>


In [ ]:
arr_tuple = np.array(my_tuple)

print(arr_tuple)
print(type(arr_tuple))

[ 1 58 63 45]
<class 'numpy.ndarray'>


### 2. Dictionary

In [ ]:
my_dict = {'one': 'uno', 
           'two': 'dos',
           'three': 'tres'}

arr_dict = np.array(my_dict)

# arr_dict[0]

# arr_dict.keys()

It's better to use transform it before to list...

In [ ]:
dict_list = list(my_dict.items())
print(dict_list)

[('one', 'uno'), ('two', 'dos'), ('three', 'tres')]


In [ ]:
arr_dict = np.array(dict_list)
print(arr_dict)

[['one' 'uno']
 ['two' 'dos']
 ['three' 'tres']]


In [ ]:
arr_dict[0]

array(['one', 'uno'], dtype='<U5')

### 3. List 

In [ ]:
list_arr = np.array(my_list)
list_arr

array([ 1, 10, 20, 75])

## Dimensions of an Array

You can index an array by row, column and dimension.

![Numpy_overview.png](attachment:Numpy_overview.png)

We can verify the array dimnsions with the function __`ndim()`__

In [ ]:
a = np.array(42)

In [ ]:
a

array(42)

In [ ]:
b = np.array([1, 2, 3, 4, 5])

In [ ]:
b

array([1, 2, 3, 4, 5])

In [ ]:
c = np.array([
    [1, 2, 3], [4, 5, 6]
])

In [ ]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d = np.array([
    [
        [1, 2, 3], [4, 5, 6]
    ], 
    [
        [1, 2, 3], [4, 5, 6]
    ]
])

In [ ]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
e = np.array([
    [
        [[1, 2, 3], [4, 5, 6]], 
        [[1, 2, 3], [4, 5, 6]],
        [[1, 2, 3], [4, 5, 6]], 
        [[1, 2, 3], [4, 5, 6]]
    ]
])

In [ ]:
e

array([[[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]]])

In [ ]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4


## Indexing sub-elements 

In [ ]:
b[0]

1

In [ ]:
c[0]

array([1, 2, 3])

In [ ]:
c[0][2]

3

In [ ]:
d[1]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d[1][0]

array([1, 2, 3])

In [ ]:
d[1][0][2]

3

In [ ]:
e[0] # Dimension 1

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
e[0][0] # Dimension 2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
e[0][0][0] # Dimension 3

array([1, 2, 3])

In [ ]:
e[0][0][0][0] # Dimension 4

1

In [ ]:
# e[0][0][0][0][0] # We haven't more dimensions...

## Shape of an array

In [ ]:
print(a.shape) # It haven't dimensions, it's just the number 42

()


In [ ]:
print(a.shape) # 1 element, length 5

()


In [ ]:
print(c.shape) # 2 elements, length 3

(2, 3)


In [ ]:
print(d.shape) # 2 elements, of 2 sub-elements, length 3

(2, 2, 3)


In [ ]:
print(e.shape) # 1 element, 
               # of 4 subelements, 
               # each sub-element, contains 2 sub-elements more
               # of lenth 3

(1, 4, 2, 3)


#### Question

What should be the dimension of this array?

In [ ]:
pregunta = np.array([
    [
        [1, 10, 100, 1000],
        [2, 20, 200, 2000],
        [3, 30, 300, 3000]
    ],
    [
        [4, 40, 400, 4000],
        [5, 50, 500, 5000],
        [6, 60, 600, 6000]
    ], 
    [
        [7, 70, 700, 7000],
        [8, 80, 800, 8000],
        [9, 90, 900, 9000]
    ]
])

## Creating _slices_ of an array

In [ ]:
my_array = np.arange(11) # start, end, steps
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
my_array[0:3]

array([0, 1, 2])

In [ ]:
my_array[2:7]

array([2, 3, 4, 5, 6])

In [ ]:
my_array[:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
my_array[6:]

array([ 6,  7,  8,  9, 10])

In [ ]:
# By steps
my_array[:9:3] 

array([0, 3, 6])

In [ ]:
my_array[6::2]

array([ 6,  8, 10])

In [ ]:
# Negative index
my_array[-2]

9

In [ ]:
my_array[:-3]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# reverse of an array
my_array[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
my_array[::-2]

array([10,  8,  6,  4,  2,  0])

## Filtering elements of an array

In [ ]:
my_array[(my_array >= 2 )] # each element >= 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
my_array[(my_array >= 2 ) & (my_array <=9)] # all elements between 2 and 9

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_array[(my_array == 2 ) | (my_array ==9)] # All elements that are equals to 2 or 9

array([2, 9])

## Reshapping the dimensions of an Array

We can define new dimensions of given array with the function __`reshape`__, for instance, create an array of 2 main elements of, 3 sub-elements each and inside each sub-element length 6

In [ ]:
np.arange(36)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
new_array = np.arange(36).reshape(2,3,6)
new_array

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [ ]:
np.arange(36).reshape(6,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35]]])

The opposite of reshape, is the function <code>__ravel__</code> and <code>__flatten__</code>, that is, remove all dimensions and leave a flat array

In [ ]:
new_array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
new_array.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

#### Question

It's possible to reshape the following array ?

In [ ]:
preg_uno = np.array([
    [10, 30, 45],
    [12, 40, 20, 10]
])

## Stacking of arrays

The stack can be made in horizontal or vertical

Let's take this arrays to explain the concepts.

In [ ]:
pair = np.array([
    [0, 2, 4],
    [6, 8, 10],
    [12, 14, 16]
])

odd = np.array([
    [1, 3, 5],
    [7, 9, 11],
    [13, 15, 17]
])

__Horizontal Stacking__

In [ ]:
np.hstack((pair, odd))

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

__Vertical Stacking__

In [ ]:
np.vstack((pair, odd))

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Also, we can use the __concatenate__ function

In [ ]:
np.concatenate((pair, odd), axis=1) # Hstack

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [ ]:
np.concatenate((pair, odd), axis=0) # Vstack

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

## Splitting arrays

Just as we can stack or join arrays, we can also split arrays into new arrays, the join criteria are very similar to the split criteria: horizontal, vertical and depth

* For horizontal split <code>**hsplit**</code>, importantly, this function takes a split value that must be equal to the number of elements in the array (per list) or, divisible by the length of the number of elements .

In [ ]:
np.hsplit(pair, 3)

[array([[ 0],
        [ 6],
        [12]]),
 array([[ 2],
        [ 8],
        [14]]),
 array([[ 4],
        [10],
        [16]])]

* For vertical splitting <code>**vsplit**</code>, importantly, this function takes a split value that must be equal to the number of elements in the array (per list) or, divisible by the length of the number of elements

In [ ]:
np.vsplit(pair, 3)

[array([[0, 2, 4]]), array([[ 6,  8, 10]]), array([[12, 14, 16]])]

Also, we can use the __split__ function

In [ ]:
np.split(pair, 3, axis=1) # Hsplit

[array([[ 0],
        [ 6],
        [12]]),
 array([[ 2],
        [ 8],
        [14]]),
 array([[ 4],
        [10],
        [16]])]

In [ ]:
np.split(pair, 3, axis=0) # Vsplit

[array([[0, 2, 4]]), array([[ 6,  8, 10]]), array([[12, 14, 16]])]

## Attributes of an array

* ndim : Dimensions of an array.

* size : Number of elements (flat array).

* itemsize : Space that each element of the array occupies in bytes

* nbytes : Size of the entire array in bytes.

* T: Transpose of the array

In [ ]:
pair.ndim

2

In [ ]:
pair.size

9

In [ ]:
pair.itemsize

4

In [ ]:
pair.nbytes

36

In [ ]:
pair.T

array([[ 0,  6, 12],
       [ 2,  8, 14],
       [ 4, 10, 16]])

## Converting arrays

It is possible to extract slices from the array or simply the entire array to obtain lists or modify the type of the array, in this case we will use two functions to perform conversions on the array.

* <code>**tolist**</code> Converts the array or a slice of it to a list

In [ ]:
my_list = pair.tolist()

In [ ]:
type(my_list)

list

* <code>**astype**</code> To modify the general type of the array

In [ ]:
pair.astype(float) # Try with str and int

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.]])

## Statistics in arrays


* __sum__ : Sum of the elements of an array.
* __empty__ : Generates an array with arbitrary values without initializing.
* __ones__ : An array of ones.
* __zeros__ : An array of zeros.
* __round__ : Round an array to n decimal places
* __fill__ : Allows you to fill an array with a value passed as a parameter.
* __mean__ : Takes the mean of the array
* __dot__ : Product of matrices
* __min__ : Minimum value of the array.
* __max__ : Maximum value of the array.
* __argmin__ : Position of the index with the minimum value
* __argmax__ : Position of the index with the maximum value
* __sort__ : Sort elements of an array.
* __eye__: Identity matrix


In [ ]:
e = np.array([[[1, 0], [0, 0]],
              [[1, 1], [1, 0]],
              [[1, 0], [0, 1]]]
            )

e.sum(axis = 0)

array([[3, 1],
       [1, 1]])

The result means that adding the columns of the first component that is:
[1. 0]
[eleven]
[1, 0]

We obtain that the rows in the column add up to 3 and in the second column 1, therefore [3, 1]

In the second component that is:
[0, 0]
[1, 0]
[0, 1]

We obtain that the rows of the first column add up to 1 and of the second 1 as well, therefore [1, 1]

In [ ]:
e.sum(axis=1)

array([[1, 0],
       [2, 1],
       [1, 1]])

In this case, each dimension works at the row level, therefore, if we add the first row which would be [1 + 0], [0 + 0] = [1, 0]

The second row: [1 + 1], [1 + 0] = [2, 1]

The third: [1 + 0], [0 + 1] = [1, 1]

If we do not specify its axis, it is calculated globally

In [ ]:
e.sum()

6

In [ ]:
print('Columns ', e.sum(axis=0))
print('Rows ', e.sum(axis=1))
print('Total ', e.sum())

Columns  [[3 1]
 [1 1]]
Rows  [[1 0]
 [2 1]
 [1 1]]
Total  6


In [ ]:
# Initialize an array
nothing = np.empty(15)
nothing

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Generate an array of ones
ones = np.ones(50)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Generate an array of zeros
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [ ]:
# Fill elements of an array
zero_array = np.zeros(20)

In [ ]:
zero_array[5:15].fill(5)
zero_array

array([0., 0., 0., 0., 0., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 0., 0.,
       0., 0., 0.])

In [ ]:
# Fill it's similar to
zero_array[:4] = 1500
zero_array

array([1500., 1500., 1500., 1500.,    0.,    5.,    5.,    5.,    5.,
          5.,    5.,    5.,    5.,    5.,    5.,    0.,    0.,    0.,
          0.,    0.])

In [ ]:
# With mean you can specify the axis to get the mean
e

array([[[1, 0],
        [0, 0]],

       [[1, 1],
        [1, 0]],

       [[1, 0],
        [0, 1]]])

In [ ]:
e.mean(axis = 0)

array([[1.        , 0.33333333],
       [0.33333333, 0.33333333]])

In [ ]:
e.mean(axis = 1)

array([[0.5, 0. ],
       [1. , 0.5],
       [0.5, 0.5]])

In [ ]:
e.mean()

0.5

In [ ]:
# Matrix product
e.dot(d)

array([[[[1, 2, 3],
         [1, 2, 3]],

        [[0, 0, 0],
         [0, 0, 0]]],


       [[[5, 7, 9],
         [5, 7, 9]],

        [[1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6]]]])

In [ ]:
# With dot function you can also multiply all values agins a vector

In [ ]:
mat = np.arange(0, 9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
vec = [10, 20, 30]
mat.dot(vec)

array([ 80, 260, 440])

In [ ]:
# min value
aux = np.array([
    [1, 100, 5],
    [2, 4, 0]
])

aux.min()

0

In [ ]:
#min value by axis
aux.min(axis=0)

array([1, 4, 0])

In [ ]:
aux.min(axis=1)

array([1, 0])

In [ ]:
# max value
print(aux.max())
print(aux.max(axis=0))
print(aux.max(axis=1))

100
[  2 100   5]
[100   4]


In [ ]:
# Index of the position with the min value
aux.argmin()

5

In [ ]:
# Index of the position with the max value
aux.argmax()

1

In [ ]:
# Sorting an array
aux = np.array([
    [1, 100, 5],
    [2, 4, 0]
])


aux.sort()

In [ ]:
# Diagonal of an array
np.diag(aux)

array([1, 2])

In [ ]:
# Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])